"""Dynamic Extraction Schemas and Models.

Defines the stable outer structure for extraction results while keeping the inner
`document` dictionary completely dynamic and schema-agnostic.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class FieldType(str, Enum):
    """Supported dynamic data types for extracted fields."""

    STRING = "string"
    NUMBER = "number"
    BOOLEAN = "boolean"
    DATE = "date"
    LIST = "list"
    OBJECT = "object"


class DynamicFieldDefinition(BaseModel):
    """Definition of a single field for dynamic schema-guided extraction."""

    name: str = Field(..., description="Unique key/name of the field")
    type: FieldType = Field(default=FieldType.STRING, description="Data type of the field")
    description: Optional[str] = Field(None, description="Guidance or description for extraction")
    required: bool = Field(default=False, description="Whether this field is mandatory")
    nested_fields: Optional[List["DynamicFieldDefinition"]] = Field(
        default=None, description="Child fields if type is OBJECT or LIST of OBJECT"
    )


class ExtractionSchema(BaseModel):
    """Dynamic schema specification provided by user or predefined template."""

    schema_name: Optional[str] = Field(default="Custom Document", description="Document type name")
    description: Optional[str] = Field(None, description="General description of document context")
    fields: List[DynamicFieldDefinition] = Field(
        default_factory=list,
        description="List of fields to dynamically extract",
    )


class ExtractedDocumentPayload(BaseModel):
    """Stable outer structure for dynamic extraction outputs."""

    document_type: str = Field(
        default="unknown_document",
        description="Identified or classified document type (e.g. invoice, contract, receipt, form, id_card, report)",
    )
    document: Dict[str, Any] = Field(
        default_factory=dict,
        description="Dynamic key-value pairs representing all extracted entities and fields",
    )
    tables: List[Any] = Field(
        default_factory=list,
        description="List of extracted tabular structures or line items",
    )
    lists: List[Any] = Field(
        default_factory=list,
        description="List of extracted enumerated lists or bullet points",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="Extraction warnings, missing required fields, or ambiguities",
    )


class ExtractionRequest(BaseModel):
    """Request payload for document extraction."""

    schema_definition: Optional[ExtractionSchema] = Field(
        default=None,
        description="Optional dynamic schema. If omitted, extraction runs in full discovery mode.",
    )
    document_base64: Optional[str] = Field(
        default=None,
        description="Base64-encoded document image or page",
    )
    raw_prompt_override: Optional[str] = Field(
        default=None,
        description="Optional custom prompt instructions to override defaults",
    )


class ExtractionResponse(BaseModel):
    """Response payload containing dynamically extracted data and execution metadata."""

    success: bool = Field(..., description="Extraction success status")
    data: ExtractedDocumentPayload = Field(
        default_factory=ExtractedDocumentPayload,
        description="Stable outer extraction payload containing dynamic document data",
    )
    raw_model_output: Optional[str] = Field(
        default=None,
        description="Raw text output generated by the VLM before parsing",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if extraction or API call failed",
    )
